:Author: anindo_7
:Email: {AuthorEmail}
:Date: 13/07/2020
:Revision: version#
:License: Public Domain

= Project: {Temperature Sensor}

Reading the current temperature from the on-chip temperature sensor.

== Step 1: Installation

1. Install Arduino IDE in your system
2. Change the baud rate to match with your chip and usb if necessary
3. Compile the sketch using Arduino IDE by selecting the proper Arduino board and port number

== Step 2: Assemble the circuit

The sketch does not require any assembly.

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 temp                	  => Arduino sketch folder
  ├── temp.ino       	  => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact anindo_7 https://id.arduino.cc/anindo_7

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
